version: "3.8"
services:  
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "8000:80"
  postgres:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
    ports:
      - "5436:5432"

